In [2]:
import pandas as pd

In [3]:
data = {
    'Category': ['A', 'A', 'B', 'B', 'A', 'B'],
    'Value': [10, 15, 20, 25, 30, 35],
    'Fee' :[20000,25000,26000,22000,24000,35000],
    'Duration':['30day','40days','35days','40days','60days','60days'],
    'Discount':[1000,2300,1200,2500,2000,2000]
}

In [4]:
df = pd.DataFrame(data)
df.head()

  Category  Value    Fee Duration  Discount
0        A     10  20000    30day      1000
1        A     15  25000   40days      2300
2        B     20  26000   35days      1200
3        B     25  22000   40days      2500
4        A     30  24000   60days      2000

In [5]:
total_sum = df['Value'].aggregate('sum')
print("Total Sum:", total_sum)

Total Sum: 135

In [6]:
df[['Value']].cumsum()

   Value
0     10
1     25
2     45
3     70
4    100
5    135

In [7]:
total_mean = df['Value'].aggregate('mean')
print("Total Mean:", total_mean)

Total Mean: 22.5

In [8]:
max_value = df['Value'].aggregate('max')
print("Maximum Value:", max_value)

Maximum Value: 35

In [9]:
count = df['Value'].aggregate('count')
print("Count of Values:", count)

Count of Values: 6

In [10]:
std = df['Value'].aggregate('std')
print("Standard Deviation:", std)

Standard Deviation: 9.354143466934854

In [11]:
result = df[['Fee', 'Discount']].aggregate('sum')
print(result)

Fee         152000
Discount     11000
dtype: int64

In [12]:
result2 = df[['Fee', 'Discount']].aggregate('sum')  
print(result2)

Fee         152000
Discount     11000
dtype: int64

In [13]:
result_group = df.groupby('Category')[['Fee', 'Discount']].aggregate('sum')
print(result_group)

            Fee  Discount
Category
A         69000      5300
B         83000      5700